# Generated by Django 5.0.6 on 2024-05-22 14:32

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("restaurant", models.CharField(max_length=100)),
                ("planned_hours", models.IntegerField()),
                ("actual_hours", models.IntegerField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sells", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "planned_actual_hours_delta",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("planned_hours"), "-", models.F("actual_hours")
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "budget_sells_delta",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("budget"), "-", models.F("sells")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=10
                        ),
                    ),
                ),
            ],
        ),
    ]
