# Generated by Django 5.0.6 on 2024-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("restaurant", models.CharField(max_length=100)),
                ("planned_hours", models.IntegerField()),
                ("actual_hours", models.IntegerField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sells", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
